### ISSUE TITLE
这个咋用啊

### ISSUE THREAD

**Issue by oorq** [spiritLHL/LotteryAutoScript_Station#1]

**Comment by spiritLHL** [comment]
配置环境修改脚本里面的路径，脚本里from Bilibili的路径删除，修改部署的IP地址

fastapi部署，前端不需要管，python run.py完事了

当然后面脚本运行得用大佬的docker版本，然后就不用管了，留意一下容器是否会因为有过期ck卡住就行了，有过期后端运行一下check接口删除过期号
