### ISSUE TITLE
如何部署在https://replit.com/上？

### ISSUE THREAD

**Issue by 8yn** [spiritLHL/LotteryAutoScript_Station#3]
https://replit.com/languages/

**Comment by spiritLHL** [comment]
emm
你需要使用抽奖的源码运行，而且需要运行两个，一个是我的站点，一个是抽奖的源码，仓库里只有我的站点，没有抽奖源码，这个你得加一下

**Comment by spiritLHL** [comment]
不知道能不能运行，因为需要两种环境，一个python一个nodejs
